// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet(arg1, arg2) {
  return window['go']['main']['App']['CreateWallet'](arg1, arg2);
}

export function GetTotalBalance(arg1) {
  return window['go']['main']['App']['GetTotalBalance'](arg1);
}

export function GetWallets(arg1) {
  return window['go']['main']['App']['GetWallets'](arg1);
}

export function InitialiseWallet(arg1) {
  return window['go']['main']['App']['InitialiseWallet'](arg1);
}

export function WalletExists() {
  return window['go']['main']['App']['WalletExists']();
}
