// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {context} from '../models';

export function CreateWallet(arg1:string,arg2:string):Promise<boolean>;

export function GetTotalBalance(arg1:string):Promise<void>;

export function GetWallets(arg1:string):Promise<Array<database.Wallet>>;

export function InitialiseWallet(arg1:string):Promise<boolean>;

export function OnDomReady(arg1:context.Context):Promise<void>;

export function WalletExists():Promise<boolean>;
